services:
  instructlab:
    build:
      context: .
      dockerfile: Dockerfile
    image: instructlab-gpu-nvidia
    container_name: instructlab-container
    volumes:
      - ${HOME}/.local/share/instructlab:/home/sandesh/.local/share/instructlab
      - ./workspace:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    tty: true
    stdin_open: true
    command: ilab
